name: Contoso-Infra-Deploy

on:
  push:
    branches:
      - main

jobs:
  prepare-deployment:
    name: Prepare Deployment
    runs-on: windows-latest
    if: ${{ success() && !cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create application change manifest
        run: |
          # Placeholder
          Start-Sleep 10
        shell: pwsh

  deploy-with-approvals:
    name: Deploy with Approvals
    runs-on: windows-latest
    needs: prepare-deployment
    if: ${{ success() && !cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create ChangeState resource
        run: |
          # Placeholder
          Start-Sleep 8
        shell: pwsh
      - name: Make progression on ChangeState resource
        run: |
          # Placeholder
          Start-Sleep 5
        shell: pwsh
      - name: Wait ChangeState to complete
        run: |
          # Placeholder
          Start-Sleep 321
        shell: pwsh
      - name: Deploy application
        run: |
          # Placeholder
          Start-Sleep 15
        shell: pwsh
