name: Contoso-Infra-Deploy

on:
  push:
    branches:
      - main

jobs:
  prepare-deployment:
    name: Prepare Deployment
    runs-on: windows-latest
    if: ${{ success() && !cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create application change manifest
        run: |
          # Placeholder
          Start-Sleep 10
        shell: pwsh

  change-safety-enforcement:
    name: ChangeSafety Enforcement
    runs-on: windows-latest
    needs: prepare-deployment
    if: ${{ success() && !cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create ChangeState resource
        run: |
          # Placeholder
          Start-Sleep 8
        shell: pwsh
      - name: Make progression on ChangeState resource
        run: |
          # Placeholder
          Start-Sleep 5
        shell: pwsh
      - name: Wait ChangeState to complete
        run: |
          # Placeholder
          Start-Sleep 321
        shell: pwsh

  deploy-via-workload-orchestrator:
    name: Deploy via Workload Orchestrator
    runs-on: windows-latest
    needs: change-safety-enforcement
    if: ${{ success() && !cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy application via Workload Orchestrator
        run: |
          # Placeholder
          Start-Sleep 16
        shell: pwsh
